// STATIC test (reads SQL text, no database): proves the identity-column expectation in scripts/db-verify.js matches
// the PostgreSQL migration AND the original MySQL schema's AUTO_INCREMENT columns, table by table.
const test = require('node:test');
const assert = require('node:assert/strict');
const fs = require('node:fs');
const path = require('node:path');

const DB = path.join(__dirname, '..', '..', 'database');
const pgSql = fs.readFileSync(path.join(DB, 'postgres', 'migrations', '001_initial_schema.sql'), 'utf8');
const mysqlSql = ['schema.sql', path.join('migrations', '001_add_password_reset_tokens.sql')]
  .map((f) => fs.readFileSync(path.join(DB, f), 'utf8')).join('\n');
const verifySrc = fs.readFileSync(path.join(__dirname, '..', 'scripts', 'db-verify.js'), 'utf8');

function tableBodies(sql) {
  const out = {};
  for (const m of sql.replace(/\r\n/g, '\n').matchAll(/CREATE TABLE (?:IF NOT EXISTS )?`?(\w+)`?\s*\(([\s\S]*?)\n\)\s*(?:ENGINE|;)/g)) out[m[1]] = m[2];
  return out;
}
const pg = tableBodies(pgSql);
const my = tableBodies(mysqlSql);

test('PostgreSQL migration defines the same 29 tables as MySQL', () => {
  assert.equal(Object.keys(pg).length, 29);
  assert.deepEqual(Object.keys(pg).sort(), Object.keys(my).sort());
});

test('a table has a PostgreSQL identity column exactly when MySQL had AUTO_INCREMENT', () => {
  const mismatches = Object.keys(pg).filter((t) => pg[t].includes('GENERATED BY DEFAULT AS IDENTITY') !== my[t].includes('AUTO_INCREMENT'));
  assert.deepEqual(mismatches, []);
});

test('exactly 26 identity tables; the three without are user_notification_preferences and the two junction tables', () => {
  const identity = Object.keys(pg).filter((t) => pg[t].includes('GENERATED BY DEFAULT AS IDENTITY'));
  const none = Object.keys(pg).filter((t) => !identity.includes(t)).sort();
  assert.equal(identity.length, 26);
  assert.deepEqual(none, ['property_amenities', 'property_comparison_items', 'user_notification_preferences']);
  // the junction tables use composite primary keys; the 1:1 table uses user_id as its key
  assert.match(pg.property_amenities, /PRIMARY KEY \(property_id, amenity_id\)/);
  assert.match(pg.property_comparison_items, /PRIMARY KEY \(comparison_id, property_id\)/);
  assert.match(pg.user_notification_preferences, /user_id\s+INTEGER\s+PRIMARY KEY/);
});

test('db-verify.js excludes exactly those three tables from its identity expectation', () => {
  const m = verifySrc.match(/IDENTITY_TABLES = TABLES\.filter\(\(t\) => !\[([^\]]*)\]\.includes\(t\)\)/);
  assert.ok(m, 'IDENTITY_TABLES definition not found');
  const excluded = [...m[1].matchAll(/'(\w+)'/g)].map((x) => x[1]).sort();
  assert.deepEqual(excluded, ['property_amenities', 'property_comparison_items', 'user_notification_preferences']);
  assert.ok(!/identity\.length === 27/.test(verifySrc), 'stale hard-coded 27 is still present');
});
