-- =====================================================================
-- EstateHub — PostgreSQL schema (Neon)
-- Translated 1:1 from database/schema.sql (MySQL 8) + migrations/001_add_password_reset_tokens.sql.
-- 29 tables, in dependency order. Applied by `npm run db:migrate` (never by the running API).
--
-- Translation rules (MySQL -> PostgreSQL):
--   INT/SMALLINT UNSIGNED AUTO_INCREMENT -> INTEGER GENERATED BY DEFAULT AS IDENTITY
--       (BY DEFAULT so existing IDs can be imported verbatim; the importer resets the sequences.)
--   SMALLINT/TINYINT UNSIGNED            -> INTEGER/SMALLINT + CHECK (>= 0)  (PG has no unsigned types)
--   ENUM(...)                            -> TEXT + named CHECK constraint (same allowed values, easy to extend)
--   BOOLEAN / TINYINT(1)                 -> BOOLEAN
--   TIMESTAMP                            -> TIMESTAMPTZ  (MySQL TIMESTAMP is an absolute instant)
--   DATETIME (appointments.scheduled_at) -> TIMESTAMP WITHOUT TIME ZONE holding UTC clock digits
--                                           (the app writes/reads explicit UTC 'YYYY-MM-DD HH:MM:SS' strings)
--   DATE                                 -> DATE
--   DECIMAL(p,s)                         -> NUMERIC(p,s)  (exact; money is never floating point)
--   JSON                                 -> JSONB
--   ON UPDATE CURRENT_TIMESTAMP          -> BEFORE UPDATE trigger (only when the row actually changed, like MySQL)
--   UNIQUE KEY on text columns           -> UNIQUE INDEX on LOWER(col): MySQL's utf8mb4_unicode_ci collation made
--                                           these case-insensitive; PostgreSQL's default is case-sensitive.
--   KEY (...)                            -> CREATE INDEX (PostgreSQL does not auto-index foreign-key columns)
-- =====================================================================

-- ---------------------------------------------------------------------
-- Trigger functions
-- ---------------------------------------------------------------------
CREATE OR REPLACE FUNCTION set_updated_at() RETURNS trigger AS $$
BEGIN
  NEW.updated_at = NOW();
  RETURN NEW;
END;
$$ LANGUAGE plpgsql;

CREATE OR REPLACE FUNCTION set_viewed_at() RETURNS trigger AS $$
BEGIN
  NEW.viewed_at = NOW();
  RETURN NEW;
END;
$$ LANGUAGE plpgsql;

-- ---------------------------------------------------------------------
-- 1. users — core identity for buyers, agents, and admins
-- ---------------------------------------------------------------------
CREATE TABLE users (
  user_id            INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  email              VARCHAR(191) NOT NULL,
  password_hash      VARCHAR(255) NOT NULL,
  role               TEXT         NOT NULL DEFAULT 'buyer',
  first_name         VARCHAR(100) NOT NULL,
  last_name          VARCHAR(100) NOT NULL,
  phone              VARCHAR(20)  NULL,
  avatar_url         VARCHAR(500) NULL,
  status             TEXT         NOT NULL DEFAULT 'active',
  email_verified_at  TIMESTAMPTZ  NULL,
  created_at         TIMESTAMPTZ  NOT NULL DEFAULT NOW(),
  updated_at         TIMESTAMPTZ  NOT NULL DEFAULT NOW(),
  CONSTRAINT chk_users_role   CHECK (role IN ('buyer','agent','admin')),
  CONSTRAINT chk_users_status CHECK (status IN ('active','pending','suspended','deactivated'))
);
CREATE UNIQUE INDEX uq_users_email ON users (LOWER(email));
CREATE INDEX idx_users_role   ON users (role);
CREATE INDEX idx_users_status ON users (status);

-- ---------------------------------------------------------------------
-- 2. property_types — lookup
-- ---------------------------------------------------------------------
CREATE TABLE property_types (
  type_id      INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name         VARCHAR(50)  NOT NULL,
  description  VARCHAR(255) NULL
);
CREATE UNIQUE INDEX uq_property_types_name ON property_types (LOWER(name));

-- ---------------------------------------------------------------------
-- 3. amenities — lookup
-- ---------------------------------------------------------------------
CREATE TABLE amenities (
  amenity_id  INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name        VARCHAR(80) NOT NULL,
  icon        VARCHAR(60) NULL
);
CREATE UNIQUE INDEX uq_amenities_name ON amenities (LOWER(name));

-- ---------------------------------------------------------------------
-- 4. locations — reusable city/neighborhood lookup (not full addresses)
--    The app stores '' (not NULL) for a missing neighborhood/state so the unique index dedupes.
-- ---------------------------------------------------------------------
CREATE TABLE locations (
  location_id   INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  neighborhood  VARCHAR(150) NULL,
  city          VARCHAR(100) NOT NULL,
  state         VARCHAR(100) NULL,
  country       VARCHAR(100) NOT NULL,
  created_at    TIMESTAMPTZ  NOT NULL DEFAULT NOW()
);
CREATE UNIQUE INDEX uq_locations_area ON locations (LOWER(neighborhood), LOWER(city), LOWER(state), LOWER(country));
CREATE INDEX idx_locations_city_country ON locations (city, country);

-- ---------------------------------------------------------------------
-- 5. admin_users — 1:1 with users where role='admin'
-- ---------------------------------------------------------------------
CREATE TABLE admin_users (
  admin_id          INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id           INTEGER     NOT NULL,
  permission_level  TEXT        NOT NULL DEFAULT 'moderator',
  created_at        TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at        TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  CONSTRAINT uq_admin_users_user_id UNIQUE (user_id),
  CONSTRAINT chk_admin_users_permission CHECK (permission_level IN ('super_admin','moderator','support')),
  CONSTRAINT fk_admin_users_user FOREIGN KEY (user_id) REFERENCES users (user_id) ON DELETE CASCADE ON UPDATE CASCADE
);

-- ---------------------------------------------------------------------
-- 6. agents — 1:1 with users where role='agent'
-- ---------------------------------------------------------------------
CREATE TABLE agents (
  agent_id             INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id              INTEGER      NOT NULL,
  license_number       VARCHAR(100) NOT NULL,
  agency_name          VARCHAR(200) NULL,
  specialty            VARCHAR(100) NULL,
  years_experience     INTEGER      NULL,
  verification_status  TEXT         NOT NULL DEFAULT 'unverified',
  verified_at          TIMESTAMPTZ  NULL,
  verified_by          INTEGER      NULL,
  license_expiry_date  DATE         NULL,
  average_rating       NUMERIC(3,2) NOT NULL DEFAULT 0.00,
  total_reviews        INTEGER      NOT NULL DEFAULT 0,
  created_at           TIMESTAMPTZ  NOT NULL DEFAULT NOW(),
  updated_at           TIMESTAMPTZ  NOT NULL DEFAULT NOW(),
  CONSTRAINT uq_agents_user_id UNIQUE (user_id),
  CONSTRAINT chk_agents_years_experience CHECK (years_experience IS NULL OR years_experience >= 0),
  CONSTRAINT chk_agents_total_reviews    CHECK (total_reviews >= 0),
  CONSTRAINT chk_agents_verification_status CHECK (verification_status IN ('unverified','pending','verified','rejected')),
  CONSTRAINT fk_agents_user        FOREIGN KEY (user_id)     REFERENCES users (user_id)        ON DELETE CASCADE  ON UPDATE CASCADE,
  CONSTRAINT fk_agents_verified_by FOREIGN KEY (verified_by) REFERENCES admin_users (admin_id) ON DELETE SET NULL ON UPDATE CASCADE
);
CREATE UNIQUE INDEX uq_agents_license_number ON agents (LOWER(license_number));
CREATE INDEX idx_agents_verification_status ON agents (verification_status);
CREATE INDEX idx_agents_license_expiry      ON agents (license_expiry_date);
CREATE INDEX idx_agents_verified_by         ON agents (verified_by);

-- ---------------------------------------------------------------------
-- 7. agent_profiles — 1:1 with agents
-- ---------------------------------------------------------------------
CREATE TABLE agent_profiles (
  agent_profile_id   INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  agent_id           INTEGER      NOT NULL,
  bio                TEXT         NULL,
  company_website    VARCHAR(255) NULL,
  office_address     VARCHAR(255) NULL,
  social_links_json  JSONB        NULL,
  created_at         TIMESTAMPTZ  NOT NULL DEFAULT NOW(),
  updated_at         TIMESTAMPTZ  NOT NULL DEFAULT NOW(),
  CONSTRAINT uq_agent_profiles_agent_id UNIQUE (agent_id),
  CONSTRAINT fk_agent_profiles_agent FOREIGN KEY (agent_id) REFERENCES agents (agent_id) ON DELETE CASCADE ON UPDATE CASCADE
);

-- ---------------------------------------------------------------------
-- 8. user_profiles — 1:1 with users (extended profile, any role)
-- ---------------------------------------------------------------------
CREATE TABLE user_profiles (
  profile_id        INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id           INTEGER      NOT NULL,
  bio               TEXT         NULL,
  address_line      VARCHAR(255) NULL,
  city              VARCHAR(100) NULL,
  state             VARCHAR(100) NULL,
  country           VARCHAR(100) NULL,
  postal_code       VARCHAR(20)  NULL,
  date_of_birth     DATE         NULL,
  preferences_json  JSONB        NULL,
  created_at        TIMESTAMPTZ  NOT NULL DEFAULT NOW(),
  updated_at        TIMESTAMPTZ  NOT NULL DEFAULT NOW(),
  CONSTRAINT uq_user_profiles_user_id UNIQUE (user_id),
  CONSTRAINT fk_user_profiles_user FOREIGN KEY (user_id) REFERENCES users (user_id) ON DELETE CASCADE ON UPDATE CASCADE
);

-- ---------------------------------------------------------------------
-- 9. refresh_tokens — JWT refresh token storage (hashed)
-- ---------------------------------------------------------------------
CREATE TABLE refresh_tokens (
  token_id    INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id     INTEGER      NOT NULL,
  token_hash  VARCHAR(255) NOT NULL,
  expires_at  TIMESTAMPTZ  NOT NULL,
  revoked_at  TIMESTAMPTZ  NULL,
  created_at  TIMESTAMPTZ  NOT NULL DEFAULT NOW(),
  CONSTRAINT uq_refresh_tokens_hash UNIQUE (token_hash),
  CONSTRAINT fk_refresh_tokens_user FOREIGN KEY (user_id) REFERENCES users (user_id) ON DELETE CASCADE ON UPDATE CASCADE
);
CREATE INDEX idx_refresh_tokens_user ON refresh_tokens (user_id);

-- ---------------------------------------------------------------------
-- 9b. password_reset_tokens — hashed, single-use (was migrations/001 in MySQL)
-- ---------------------------------------------------------------------
CREATE TABLE password_reset_tokens (
  reset_token_id  INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id         INTEGER      NOT NULL,
  token_hash      VARCHAR(255) NOT NULL,
  expires_at      TIMESTAMPTZ  NOT NULL,
  used_at         TIMESTAMPTZ  NULL,
  created_at      TIMESTAMPTZ  NOT NULL DEFAULT NOW(),
  CONSTRAINT uq_password_reset_tokens_hash UNIQUE (token_hash),
  CONSTRAINT fk_password_reset_tokens_user FOREIGN KEY (user_id) REFERENCES users (user_id) ON DELETE CASCADE ON UPDATE CASCADE
);
CREATE INDEX idx_password_reset_tokens_user ON password_reset_tokens (user_id);

-- ---------------------------------------------------------------------
-- 10. user_notification_preferences — 1:1 with users
-- ---------------------------------------------------------------------
CREATE TABLE user_notification_preferences (
  user_id              INTEGER     PRIMARY KEY,
  email_notifications  BOOLEAN     NOT NULL DEFAULT TRUE,
  sms_notifications    BOOLEAN     NOT NULL DEFAULT FALSE,
  push_notifications   BOOLEAN     NOT NULL DEFAULT TRUE,
  updated_at           TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  CONSTRAINT fk_notif_prefs_user FOREIGN KEY (user_id) REFERENCES users (user_id) ON DELETE CASCADE ON UPDATE CASCADE
);

-- ---------------------------------------------------------------------
-- 11. system_notification_settings — admin-configured global triggers
-- ---------------------------------------------------------------------
CREATE TABLE system_notification_settings (
  setting_id     INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  event_key      VARCHAR(80)  NOT NULL,
  description    VARCHAR(255) NULL,
  email_enabled  BOOLEAN      NOT NULL DEFAULT TRUE,
  sms_enabled    BOOLEAN      NOT NULL DEFAULT FALSE,
  updated_by     INTEGER      NULL,
  updated_at     TIMESTAMPTZ  NOT NULL DEFAULT NOW(),
  CONSTRAINT fk_sys_notif_settings_admin FOREIGN KEY (updated_by) REFERENCES admin_users (admin_id) ON DELETE SET NULL ON UPDATE CASCADE
);
CREATE UNIQUE INDEX uq_system_notification_settings_event_key ON system_notification_settings (LOWER(event_key));
CREATE INDEX idx_system_notification_settings_updated_by ON system_notification_settings (updated_by);

-- ---------------------------------------------------------------------
-- 12. properties — core listing table
-- ---------------------------------------------------------------------
CREATE TABLE properties (
  property_id        INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  listed_by_user_id  INTEGER       NOT NULL,
  agent_id           INTEGER       NULL,
  type_id            INTEGER       NOT NULL,
  location_id        INTEGER       NOT NULL,
  title              VARCHAR(200)  NOT NULL,
  description        TEXT          NULL,
  address_line       VARCHAR(255)  NOT NULL,
  postal_code        VARCHAR(20)   NULL,
  latitude           NUMERIC(10,8) NULL,
  longitude          NUMERIC(11,8) NULL,
  price              NUMERIC(14,2) NOT NULL,
  listing_type       TEXT          NOT NULL DEFAULT 'sale',
  bedrooms           INTEGER       NULL,
  bathrooms          NUMERIC(3,1)  NULL,
  area_sqft          INTEGER       NULL,
  lot_size_sqft      INTEGER       NULL,
  year_built         INTEGER       NULL,
  status             TEXT          NOT NULL DEFAULT 'draft',
  is_featured        BOOLEAN       NOT NULL DEFAULT FALSE,
  view_count         INTEGER       NOT NULL DEFAULT 0,
  rejection_reason   TEXT          NULL,
  approved_by        INTEGER       NULL,
  approved_at        TIMESTAMPTZ   NULL,
  created_at         TIMESTAMPTZ   NOT NULL DEFAULT NOW(),
  updated_at         TIMESTAMPTZ   NOT NULL DEFAULT NOW(),
  CONSTRAINT chk_properties_listing_type CHECK (listing_type IN ('sale','rent')),
  CONSTRAINT chk_properties_status CHECK (status IN ('draft','pending_review','active','under_contract','sold','rejected','archived')),
  CONSTRAINT chk_properties_bedrooms      CHECK (bedrooms IS NULL OR bedrooms >= 0),
  CONSTRAINT chk_properties_bathrooms     CHECK (bathrooms IS NULL OR bathrooms >= 0),
  CONSTRAINT chk_properties_area_sqft     CHECK (area_sqft IS NULL OR area_sqft >= 0),
  CONSTRAINT chk_properties_lot_size_sqft CHECK (lot_size_sqft IS NULL OR lot_size_sqft >= 0),
  CONSTRAINT chk_properties_year_built    CHECK (year_built IS NULL OR year_built >= 0),
  CONSTRAINT chk_properties_view_count    CHECK (view_count >= 0),
  CONSTRAINT fk_properties_listed_by   FOREIGN KEY (listed_by_user_id) REFERENCES users (user_id)          ON DELETE CASCADE  ON UPDATE CASCADE,
  CONSTRAINT fk_properties_agent       FOREIGN KEY (agent_id)          REFERENCES agents (agent_id)        ON DELETE SET NULL ON UPDATE CASCADE,
  CONSTRAINT fk_properties_type        FOREIGN KEY (type_id)           REFERENCES property_types (type_id) ON DELETE RESTRICT ON UPDATE CASCADE,
  CONSTRAINT fk_properties_location    FOREIGN KEY (location_id)       REFERENCES locations (location_id)  ON DELETE RESTRICT ON UPDATE CASCADE,
  CONSTRAINT fk_properties_approved_by FOREIGN KEY (approved_by)       REFERENCES admin_users (admin_id)   ON DELETE SET NULL ON UPDATE CASCADE
);
CREATE INDEX idx_properties_status      ON properties (status);
CREATE INDEX idx_properties_price       ON properties (price);
CREATE INDEX idx_properties_location    ON properties (location_id);
CREATE INDEX idx_properties_type        ON properties (type_id);
CREATE INDEX idx_properties_bedrooms    ON properties (bedrooms);
CREATE INDEX idx_properties_agent       ON properties (agent_id);
CREATE INDEX idx_properties_listed_by   ON properties (listed_by_user_id);
CREATE INDEX idx_properties_approved_by ON properties (approved_by);
CREATE INDEX idx_properties_search      ON properties (status, listing_type, price, bedrooms);

-- ---------------------------------------------------------------------
-- 13. property_images
-- ---------------------------------------------------------------------
CREATE TABLE property_images (
  image_id       INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  property_id    INTEGER      NOT NULL,
  image_url      VARCHAR(500) NOT NULL,
  alt_text       VARCHAR(255) NULL,
  is_primary     BOOLEAN      NOT NULL DEFAULT FALSE,
  display_order  INTEGER      NOT NULL DEFAULT 0,
  created_at     TIMESTAMPTZ  NOT NULL DEFAULT NOW(),
  CONSTRAINT chk_property_images_display_order CHECK (display_order >= 0),
  CONSTRAINT fk_property_images_property FOREIGN KEY (property_id) REFERENCES properties (property_id) ON DELETE CASCADE ON UPDATE CASCADE
);
CREATE INDEX idx_property_images_property ON property_images (property_id);

-- ---------------------------------------------------------------------
-- 14. property_amenities — M:N junction
-- ---------------------------------------------------------------------
CREATE TABLE property_amenities (
  property_id  INTEGER NOT NULL,
  amenity_id   INTEGER NOT NULL,
  PRIMARY KEY (property_id, amenity_id),
  CONSTRAINT fk_property_amenities_property FOREIGN KEY (property_id) REFERENCES properties (property_id) ON DELETE CASCADE ON UPDATE CASCADE,
  CONSTRAINT fk_property_amenities_amenity  FOREIGN KEY (amenity_id)  REFERENCES amenities (amenity_id)   ON DELETE CASCADE ON UPDATE CASCADE
);
CREATE INDEX idx_property_amenities_amenity ON property_amenities (amenity_id);

-- ---------------------------------------------------------------------
-- 15. favorites — "Saved Properties"
-- ---------------------------------------------------------------------
CREATE TABLE favorites (
  favorite_id  INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id      INTEGER     NOT NULL,
  property_id  INTEGER     NOT NULL,
  created_at   TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  CONSTRAINT uq_favorites_user_property UNIQUE (user_id, property_id),
  CONSTRAINT fk_favorites_user     FOREIGN KEY (user_id)     REFERENCES users (user_id)          ON DELETE CASCADE ON UPDATE CASCADE,
  CONSTRAINT fk_favorites_property FOREIGN KEY (property_id) REFERENCES properties (property_id) ON DELETE CASCADE ON UPDATE CASCADE
);
CREATE INDEX idx_favorites_property ON favorites (property_id);

-- ---------------------------------------------------------------------
-- 16. recently_viewed_properties
-- ---------------------------------------------------------------------
CREATE TABLE recently_viewed_properties (
  view_id      INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id      INTEGER     NOT NULL,
  property_id  INTEGER     NOT NULL,
  viewed_at    TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  CONSTRAINT uq_recently_viewed_user_property UNIQUE (user_id, property_id),
  CONSTRAINT fk_recently_viewed_user     FOREIGN KEY (user_id)     REFERENCES users (user_id)          ON DELETE CASCADE ON UPDATE CASCADE,
  CONSTRAINT fk_recently_viewed_property FOREIGN KEY (property_id) REFERENCES properties (property_id) ON DELETE CASCADE ON UPDATE CASCADE
);
CREATE INDEX idx_recently_viewed_property ON recently_viewed_properties (property_id);

-- ---------------------------------------------------------------------
-- 17. property_comparisons
-- ---------------------------------------------------------------------
CREATE TABLE property_comparisons (
  comparison_id  INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id        INTEGER     NOT NULL,
  created_at     TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  CONSTRAINT fk_property_comparisons_user FOREIGN KEY (user_id) REFERENCES users (user_id) ON DELETE CASCADE ON UPDATE CASCADE
);
CREATE INDEX idx_property_comparisons_user ON property_comparisons (user_id);

-- ---------------------------------------------------------------------
-- 18. property_comparison_items — M:N junction
-- ---------------------------------------------------------------------
CREATE TABLE property_comparison_items (
  comparison_id  INTEGER     NOT NULL,
  property_id    INTEGER     NOT NULL,
  added_at       TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  PRIMARY KEY (comparison_id, property_id),
  CONSTRAINT fk_comparison_items_comparison FOREIGN KEY (comparison_id) REFERENCES property_comparisons (comparison_id) ON DELETE CASCADE ON UPDATE CASCADE,
  CONSTRAINT fk_comparison_items_property   FOREIGN KEY (property_id)   REFERENCES properties (property_id)             ON DELETE CASCADE ON UPDATE CASCADE
);
CREATE INDEX idx_comparison_items_property ON property_comparison_items (property_id);

-- ---------------------------------------------------------------------
-- 19. inquiries — "Contact Agent" form submissions
-- ---------------------------------------------------------------------
CREATE TABLE inquiries (
  inquiry_id            INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  property_id           INTEGER     NOT NULL,
  user_id               INTEGER     NOT NULL,
  agent_id              INTEGER     NULL,
  message               TEXT        NOT NULL,
  preferred_visit_date  DATE        NULL,
  status                TEXT        NOT NULL DEFAULT 'new',
  created_at            TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at            TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  CONSTRAINT chk_inquiries_status CHECK (status IN ('new','contacted','closed')),
  CONSTRAINT fk_inquiries_property FOREIGN KEY (property_id) REFERENCES properties (property_id) ON DELETE CASCADE  ON UPDATE CASCADE,
  CONSTRAINT fk_inquiries_user     FOREIGN KEY (user_id)     REFERENCES users (user_id)          ON DELETE CASCADE  ON UPDATE CASCADE,
  CONSTRAINT fk_inquiries_agent    FOREIGN KEY (agent_id)    REFERENCES agents (agent_id)        ON DELETE SET NULL ON UPDATE CASCADE
);
CREATE INDEX idx_inquiries_property ON inquiries (property_id);
CREATE INDEX idx_inquiries_status   ON inquiries (status);
CREATE INDEX idx_inquiries_user     ON inquiries (user_id);
CREATE INDEX idx_inquiries_agent    ON inquiries (agent_id);

-- ---------------------------------------------------------------------
-- 20. license_renewals
-- ---------------------------------------------------------------------
CREATE TABLE license_renewals (
  renewal_id              INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  agent_id                INTEGER     NOT NULL,
  current_license_expiry  DATE        NOT NULL,
  status                  TEXT        NOT NULL DEFAULT 'draft',
  submitted_at            TIMESTAMPTZ NULL,
  reviewed_by             INTEGER     NULL,
  reviewed_at             TIMESTAMPTZ NULL,
  new_expiry_date         DATE        NULL,
  created_at              TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at              TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  CONSTRAINT chk_license_renewals_status CHECK (status IN ('draft','documents_pending','submitted','under_review','missing_documents','approved','rejected')),
  CONSTRAINT fk_license_renewals_agent       FOREIGN KEY (agent_id)    REFERENCES agents (agent_id)        ON DELETE CASCADE  ON UPDATE CASCADE,
  CONSTRAINT fk_license_renewals_reviewed_by FOREIGN KEY (reviewed_by) REFERENCES admin_users (admin_id)   ON DELETE SET NULL ON UPDATE CASCADE
);
CREATE INDEX idx_license_renewals_agent       ON license_renewals (agent_id);
CREATE INDEX idx_license_renewals_status      ON license_renewals (status);
CREATE INDEX idx_license_renewals_reviewed_by ON license_renewals (reviewed_by);

-- ---------------------------------------------------------------------
-- 21. verification_documents — unified for initial verification + renewals
-- ---------------------------------------------------------------------
CREATE TABLE verification_documents (
  document_id       INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  agent_id          INTEGER      NOT NULL,
  renewal_id        INTEGER      NULL,
  document_type     TEXT         NOT NULL,
  file_url          VARCHAR(500) NOT NULL,
  status            TEXT         NOT NULL DEFAULT 'pending',
  rejection_reason  TEXT         NULL,
  reviewed_by       INTEGER      NULL,
  reviewed_at       TIMESTAMPTZ  NULL,
  uploaded_at       TIMESTAMPTZ  NOT NULL DEFAULT NOW(),
  CONSTRAINT chk_verification_documents_type   CHECK (document_type IN ('license','insurance','certification','id_proof','other')),
  CONSTRAINT chk_verification_documents_status CHECK (status IN ('pending','verified','rejected')),
  CONSTRAINT fk_verification_documents_agent       FOREIGN KEY (agent_id)    REFERENCES agents (agent_id)                ON DELETE CASCADE  ON UPDATE CASCADE,
  CONSTRAINT fk_verification_documents_renewal     FOREIGN KEY (renewal_id)  REFERENCES license_renewals (renewal_id)    ON DELETE CASCADE  ON UPDATE CASCADE,
  CONSTRAINT fk_verification_documents_reviewed_by FOREIGN KEY (reviewed_by) REFERENCES admin_users (admin_id)           ON DELETE SET NULL ON UPDATE CASCADE
);
CREATE INDEX idx_verification_documents_agent       ON verification_documents (agent_id);
CREATE INDEX idx_verification_documents_status      ON verification_documents (status);
CREATE INDEX idx_verification_documents_renewal     ON verification_documents (renewal_id);
CREATE INDEX idx_verification_documents_reviewed_by ON verification_documents (reviewed_by);

-- ---------------------------------------------------------------------
-- 22. conversations
--     UNIQUE (buyer, agent, property): a NULL property_id never collides (NULLs are distinct in both
--     MySQL and PostgreSQL), exactly like before.
-- ---------------------------------------------------------------------
CREATE TABLE conversations (
  conversation_id  INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  property_id      INTEGER     NULL,
  inquiry_id       INTEGER     NULL,
  buyer_id         INTEGER     NOT NULL,
  agent_user_id    INTEGER     NOT NULL,
  last_message_at  TIMESTAMPTZ NULL,
  created_at       TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  CONSTRAINT uq_conversations_participants UNIQUE (buyer_id, agent_user_id, property_id),
  CONSTRAINT fk_conversations_property   FOREIGN KEY (property_id)   REFERENCES properties (property_id) ON DELETE SET NULL ON UPDATE CASCADE,
  CONSTRAINT fk_conversations_inquiry    FOREIGN KEY (inquiry_id)    REFERENCES inquiries (inquiry_id)   ON DELETE SET NULL ON UPDATE CASCADE,
  CONSTRAINT fk_conversations_buyer      FOREIGN KEY (buyer_id)      REFERENCES users (user_id)          ON DELETE CASCADE  ON UPDATE CASCADE,
  CONSTRAINT fk_conversations_agent_user FOREIGN KEY (agent_user_id) REFERENCES users (user_id)          ON DELETE CASCADE  ON UPDATE CASCADE
);
CREATE INDEX idx_conversations_property   ON conversations (property_id);
CREATE INDEX idx_conversations_inquiry    ON conversations (inquiry_id);
CREATE INDEX idx_conversations_agent_user ON conversations (agent_user_id);

-- ---------------------------------------------------------------------
-- 23. messages
-- ---------------------------------------------------------------------
CREATE TABLE messages (
  message_id       INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  conversation_id  INTEGER     NOT NULL,
  sender_id        INTEGER     NOT NULL,
  message_text     TEXT        NOT NULL,
  is_read          BOOLEAN     NOT NULL DEFAULT FALSE,
  created_at       TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  CONSTRAINT fk_messages_conversation FOREIGN KEY (conversation_id) REFERENCES conversations (conversation_id) ON DELETE CASCADE ON UPDATE CASCADE,
  CONSTRAINT fk_messages_sender       FOREIGN KEY (sender_id)       REFERENCES users (user_id)                 ON DELETE CASCADE ON UPDATE CASCADE
);
CREATE INDEX idx_messages_conversation_created ON messages (conversation_id, created_at);
CREATE INDEX idx_messages_sender               ON messages (sender_id);

-- ---------------------------------------------------------------------
-- 24. appointments — property viewings
--     scheduled_at is TIMESTAMP WITHOUT TIME ZONE on purpose: it holds UTC clock digits written and read as
--     explicit 'YYYY-MM-DD HH:MM:SS' strings by utils/appointmentRules.js (same as MySQL DATETIME).
-- ---------------------------------------------------------------------
CREATE TABLE appointments (
  appointment_id    INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  property_id       INTEGER     NOT NULL,
  user_id           INTEGER     NOT NULL,
  agent_id          INTEGER     NOT NULL,
  scheduled_at      TIMESTAMP   NOT NULL,
  duration_minutes  INTEGER     NOT NULL DEFAULT 30,
  status            TEXT        NOT NULL DEFAULT 'requested',
  notes             TEXT        NULL,
  created_at        TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at        TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  CONSTRAINT chk_appointments_duration CHECK (duration_minutes >= 0),
  CONSTRAINT chk_appointments_status   CHECK (status IN ('requested','confirmed','completed','cancelled','no_show')),
  CONSTRAINT fk_appointments_property FOREIGN KEY (property_id) REFERENCES properties (property_id) ON DELETE CASCADE ON UPDATE CASCADE,
  CONSTRAINT fk_appointments_user     FOREIGN KEY (user_id)     REFERENCES users (user_id)          ON DELETE CASCADE ON UPDATE CASCADE,
  CONSTRAINT fk_appointments_agent    FOREIGN KEY (agent_id)    REFERENCES agents (agent_id)        ON DELETE CASCADE ON UPDATE CASCADE
);
CREATE INDEX idx_appointments_agent_time ON appointments (agent_id, scheduled_at);
CREATE INDEX idx_appointments_user       ON appointments (user_id);
CREATE INDEX idx_appointments_property   ON appointments (property_id);
CREATE INDEX idx_appointments_status     ON appointments (status);

-- ---------------------------------------------------------------------
-- 25. agent_reviews
-- ---------------------------------------------------------------------
CREATE TABLE agent_reviews (
  review_id   INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  agent_id    INTEGER     NOT NULL,
  user_id     INTEGER     NOT NULL,
  rating      SMALLINT    NOT NULL,
  comment     TEXT        NULL,
  created_at  TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at  TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  CONSTRAINT uq_agent_reviews_agent_user UNIQUE (agent_id, user_id),
  CONSTRAINT chk_agent_reviews_rating CHECK (rating BETWEEN 1 AND 5),
  CONSTRAINT fk_agent_reviews_agent FOREIGN KEY (agent_id) REFERENCES agents (agent_id) ON DELETE CASCADE ON UPDATE CASCADE,
  CONSTRAINT fk_agent_reviews_user  FOREIGN KEY (user_id)  REFERENCES users (user_id)   ON DELETE CASCADE ON UPDATE CASCADE
);
CREATE INDEX idx_agent_reviews_user ON agent_reviews (user_id);

-- ---------------------------------------------------------------------
-- 26. property_reviews
-- ---------------------------------------------------------------------
CREATE TABLE property_reviews (
  review_id    INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  property_id  INTEGER     NOT NULL,
  user_id      INTEGER     NOT NULL,
  rating       SMALLINT    NOT NULL,
  comment      TEXT        NULL,
  created_at   TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at   TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  CONSTRAINT uq_property_reviews_property_user UNIQUE (property_id, user_id),
  CONSTRAINT chk_property_reviews_rating CHECK (rating BETWEEN 1 AND 5),
  CONSTRAINT fk_property_reviews_property FOREIGN KEY (property_id) REFERENCES properties (property_id) ON DELETE CASCADE ON UPDATE CASCADE,
  CONSTRAINT fk_property_reviews_user     FOREIGN KEY (user_id)     REFERENCES users (user_id)          ON DELETE CASCADE ON UPDATE CASCADE
);
CREATE INDEX idx_property_reviews_user ON property_reviews (user_id);

-- ---------------------------------------------------------------------
-- 27. notifications — in-app, per user
-- ---------------------------------------------------------------------
CREATE TABLE notifications (
  notification_id      INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id              INTEGER      NOT NULL,
  type                 VARCHAR(50)  NOT NULL,
  title                VARCHAR(150) NOT NULL,
  body                 TEXT         NULL,
  related_entity_type  VARCHAR(50)  NULL,
  related_entity_id    INTEGER      NULL,
  is_read              BOOLEAN      NOT NULL DEFAULT FALSE,
  created_at           TIMESTAMPTZ  NOT NULL DEFAULT NOW(),
  CONSTRAINT fk_notifications_user FOREIGN KEY (user_id) REFERENCES users (user_id) ON DELETE CASCADE ON UPDATE CASCADE
);
CREATE INDEX idx_notifications_user_unread ON notifications (user_id, is_read);

-- ---------------------------------------------------------------------
-- 28. admin_action_log — generic audit trail
-- ---------------------------------------------------------------------
CREATE TABLE admin_action_log (
  log_id       INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  admin_id     INTEGER     NOT NULL,
  action_type  VARCHAR(60) NOT NULL,
  target_type  VARCHAR(40) NOT NULL,
  target_id    INTEGER     NOT NULL,
  notes        TEXT        NULL,
  created_at   TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  CONSTRAINT fk_admin_action_log_admin FOREIGN KEY (admin_id) REFERENCES admin_users (admin_id) ON DELETE CASCADE ON UPDATE CASCADE
);
CREATE INDEX idx_admin_action_log_target ON admin_action_log (target_type, target_id);
CREATE INDEX idx_admin_action_log_admin  ON admin_action_log (admin_id);

-- ---------------------------------------------------------------------
-- ON UPDATE CURRENT_TIMESTAMP replacements. WHEN (OLD.* IS DISTINCT FROM NEW.*) reproduces MySQL's
-- behaviour of only bumping the timestamp when a row actually changed.
-- ---------------------------------------------------------------------
CREATE TRIGGER trg_users_updated_at                        BEFORE UPDATE ON users                        FOR EACH ROW WHEN (OLD.* IS DISTINCT FROM NEW.*) EXECUTE FUNCTION set_updated_at();
CREATE TRIGGER trg_admin_users_updated_at                  BEFORE UPDATE ON admin_users                  FOR EACH ROW WHEN (OLD.* IS DISTINCT FROM NEW.*) EXECUTE FUNCTION set_updated_at();
CREATE TRIGGER trg_agents_updated_at                       BEFORE UPDATE ON agents                       FOR EACH ROW WHEN (OLD.* IS DISTINCT FROM NEW.*) EXECUTE FUNCTION set_updated_at();
CREATE TRIGGER trg_agent_profiles_updated_at               BEFORE UPDATE ON agent_profiles               FOR EACH ROW WHEN (OLD.* IS DISTINCT FROM NEW.*) EXECUTE FUNCTION set_updated_at();
CREATE TRIGGER trg_user_profiles_updated_at                BEFORE UPDATE ON user_profiles                FOR EACH ROW WHEN (OLD.* IS DISTINCT FROM NEW.*) EXECUTE FUNCTION set_updated_at();
CREATE TRIGGER trg_user_notification_preferences_updated   BEFORE UPDATE ON user_notification_preferences FOR EACH ROW WHEN (OLD.* IS DISTINCT FROM NEW.*) EXECUTE FUNCTION set_updated_at();
CREATE TRIGGER trg_system_notification_settings_updated    BEFORE UPDATE ON system_notification_settings FOR EACH ROW WHEN (OLD.* IS DISTINCT FROM NEW.*) EXECUTE FUNCTION set_updated_at();
CREATE TRIGGER trg_properties_updated_at                   BEFORE UPDATE ON properties                   FOR EACH ROW WHEN (OLD.* IS DISTINCT FROM NEW.*) EXECUTE FUNCTION set_updated_at();
CREATE TRIGGER trg_inquiries_updated_at                    BEFORE UPDATE ON inquiries                    FOR EACH ROW WHEN (OLD.* IS DISTINCT FROM NEW.*) EXECUTE FUNCTION set_updated_at();
CREATE TRIGGER trg_license_renewals_updated_at             BEFORE UPDATE ON license_renewals             FOR EACH ROW WHEN (OLD.* IS DISTINCT FROM NEW.*) EXECUTE FUNCTION set_updated_at();
CREATE TRIGGER trg_appointments_updated_at                 BEFORE UPDATE ON appointments                 FOR EACH ROW WHEN (OLD.* IS DISTINCT FROM NEW.*) EXECUTE FUNCTION set_updated_at();
CREATE TRIGGER trg_agent_reviews_updated_at                BEFORE UPDATE ON agent_reviews                FOR EACH ROW WHEN (OLD.* IS DISTINCT FROM NEW.*) EXECUTE FUNCTION set_updated_at();
CREATE TRIGGER trg_property_reviews_updated_at             BEFORE UPDATE ON property_reviews             FOR EACH ROW WHEN (OLD.* IS DISTINCT FROM NEW.*) EXECUTE FUNCTION set_updated_at();
CREATE TRIGGER trg_recently_viewed_viewed_at               BEFORE UPDATE ON recently_viewed_properties   FOR EACH ROW WHEN (OLD.* IS DISTINCT FROM NEW.*) EXECUTE FUNCTION set_viewed_at();
